# Plugin Definition below. This is essentially a valid helm values file that will be merged
# with the other vcluster values during vcluster create or helm install.
plugin:
  vcluster-plugin:
    version: v2
    image: ghcr.io/appscode/vcluster-plugin:v0.0.1
    rbac:
      role:
        extraRules:
          - apiGroups: ["cacerts.csi.cert-manager.io"]
            resources: ["caproviderclasses"]
            verbs: ["*"]
      clusterRole:
        extraRules:
          - apiGroups: ["apiextensions.k8s.io"]
            resources: ["customresourcedefinitions"]
            verbs: ["*"]

# Make sure the cluster role is enabled or otherwise the plugin won't be able to watch custom
# resource definitions.
rbac:
  clusterRole:
    create: true
  role:
    extended: true
